export const ipcChannels = {
  mods: {
    browse: "mods:browse",
    details: "mods:details",
    installed: "mods:installed",
    previewSyncFromModList: "mods:preview-sync-from-mod-list",
    syncFromModList: "mods:sync-from-mod-list",
    deleteInstalled: "mods:delete-installed",
    queueUpdateInstalled: "mods:queue-update-installed",
    queueUpdateAllInstalled: "mods:queue-update-all-installed",
    setEnabled: "mods:set-enabled",
    getLibraryState: "mods:get-library-state",
    getModToggleImpact: "mods:get-mod-toggle-impact",
    getLatestVersions: "mods:get-latest-versions",
    getInstalledConflicts: "mods:get-installed-conflicts",
    createModListProfile: "mods:create-mod-list-profile",
    renameModListProfile: "mods:rename-mod-list-profile",
    switchModListProfile: "mods:switch-mod-list-profile",
    removeModListProfile: "mods:remove-mod-list-profile",
    diffModListProfiles: "mods:diff-mod-list-profiles",
    exportModListProfile: "mods:export-mod-list-profile",
    importModListProfile: "mods:import-mod-list-profile",
  },
  downloads: {
    enqueue: "downloads:enqueue",
    list: "downloads:list",
    retry: "downloads:retry",
    subscribe: "downloads:progress",
    unsubscribe: "downloads:unsubscribe",
  },
  settings: {
    get: "settings:get",
    update: "settings:update",
    chooseFolder: "settings:choose-folder",
    chooseModListFile: "settings:choose-mod-list-file",
    chooseFactorioExecutable: "settings:choose-factorio-executable",
  },
  app: {
    meta: "app:meta",
    updateState: "app:update-state",
    checkForUpdates: "app:check-for-updates",
    downloadUpdate: "app:download-update",
    quitAndInstallUpdate: "app:quit-and-install-update",
    subscribeToUpdates: "app:update-progress",
  },
  external: {
    openUrl: "external:open-url",
    openPath: "external:open-path",
  },
  launch: {
    launchFactorio: "launch:launch-factorio",
  },
} as const;
